name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        app: [battary-indicator, yarurf-balance-checker]
        include:
          - os: ubuntu-latest
            suffix: linux
            ext: ""
            archive: tar.gz
          - os: windows-latest
            suffix: windows
            ext: ".exe"
            archive: zip
          - os: macos-latest
            suffix: darwin
            ext: ""
            archive: tar.gz

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build merge_events
      run: |
        make all ext=${{ matrix.ext }}

    - name: Compress binaries
      run: |
        mkdir -p dist
        if [[ ${{ matrix.os }} == "windows-latest" ]]; then
            Compress-Archive -Path bin/${{ matrix.app }} -DestinationPath dist/${{ matrix.app }}-${{ matrix.suffix }}.${{ matrix.archive}}
        else
            tar -czf dist/${{ matrix.app }}-${{ matrix.suffix }}.${{ matrix.archive}} bin/${{ matrix.app }}

    - name: Upload compressed binaries
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.app }}-${{ matrix.suffix }}
        path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Compress binaries
        run: |
          ls -la dist